export const DASHBOARD_PERIODS = [
  { value: 'today', label: 'Hari ini' },
  { value: 'week', label: '7 hari' },
  { value: 'month', label: '30 hari' },
  { value: 'semester', label: 'Semester' },
]

export const adminDashboardData = {
  today: {
    summary: 'Monitor cepat untuk validasi, distribusi survei, dan risiko wilayah yang butuh keputusan admin.',
    cards: [
      { title: 'Survei Masuk', value: '284', subtitle: '118 sudah tervalidasi sejak pagi', trend: 12, color: 'teal' },
      { title: 'Antrian Validasi', value: '46', subtitle: '17 item berstatus prioritas tinggi', trend: -4, color: 'amber' },
      { title: 'Intervensi Aktif', value: '133', subtitle: '48 keluarga perlu kunjungan ulang', trend: 9, color: 'rose' },
      { title: 'Sinkronisasi Unit', value: '22/24', subtitle: 'Dua unit belum kirim data terbaru', trend: 3, color: 'blue' },
    ],
    spotlight: [
      { label: 'Wilayah perlu atensi', value: 'Kec. Harapan', detail: 'IKS stagnan 3 pekan dan revisi survei tertinggi.' },
      { label: 'Petugas terpadat', value: 'Tim Verifikator 2', detail: 'Menangani 19 validasi lintas puskesmas hari ini.' },
      { label: 'Aksi tercepat', value: 'Buka validasi', detail: 'Dorong item menunggu agar laporan harian stabil.' },
    ],
    funnel: [
      { label: 'Masuk', value: 284, hint: 'Data diterima sistem' },
      { label: 'Dicek', value: 196, hint: 'Sedang diverifikasi' },
      { label: 'Valid', value: 118, hint: 'Siap agregasi laporan' },
      { label: 'Revisi', value: 31, hint: 'Perlu perbaikan lapangan' },
    ],
    quickActions: [
      { label: 'Validasi Data', path: '/admin/surveys/validation', description: 'Tinjau antrean survey terbaru dan selesaikan revisi.' },
      { label: 'Database Keluarga', path: '/admin/surveys/database', description: 'Pastikan struktur keluarga dan riwayat tetap bersih.' },
      { label: 'Monitoring Intervensi', path: '/admin/surveys/interventions', description: 'Lihat tindak lanjut keluarga berstatus tidak sehat.' },
      { label: 'Laporan Progress', path: '/admin/reports/survey-progress', description: 'Cek target vs realisasi lintas wilayah.' },
    ],
    activities: [
      { title: 'Validasi lintas wilayah', status: 'Perlu keputusan', tone: 'warning', meta: '12 menit lalu', description: '8 survei dari Puskesmas Sukamaju tertahan karena bukti kunjungan belum lengkap.' },
      { title: 'Master wilayah diperbarui', status: 'Selesai sinkron', tone: 'success', meta: '39 menit lalu', description: 'Penyesuaian desa binaan sudah terbaca di modul laporan dan survei.' },
      { title: 'Hotspot indikator merokok', status: 'Naik cepat', tone: 'danger', meta: '1 jam lalu', description: 'Tiga desa menunjukkan lonjakan keluarga dengan anggota perokok aktif.' },
    ],
    rows: [
      { area: 'Kec. Sukamaju', target: '1.240', realized: '1.118', coverage: '90%', valid: '94%', risk: 'Stabil' },
      { area: 'Kec. Harapan', target: '1.050', realized: '804', coverage: '77%', valid: '82%', risk: 'Perlu eskalasi' },
      { area: 'Kec. Cempaka', target: '980', realized: '936', coverage: '95%', valid: '96%', risk: 'Baik' },
      { area: 'Kec. Mekarsari', target: '1.120', realized: '1.004', coverage: '90%', valid: '88%', risk: 'Pantau revisi' },
    ],
  },
  week: {
    summary: 'Gambaran 7 hari untuk performa operasional, backlog validasi, dan wilayah yang mulai tertinggal.',
    cards: [
      { title: 'Survei Masuk', value: '1.842', subtitle: 'Rata-rata 263 survei per hari', trend: 8, color: 'teal' },
      { title: 'Antrian Validasi', value: '129', subtitle: 'Turun dari 151 pekan lalu', trend: -15, color: 'amber' },
      { title: 'Intervensi Aktif', value: '438', subtitle: '93 keluarga belum punya jadwal follow-up', trend: 5, color: 'rose' },
      { title: 'Sinkronisasi Unit', value: '24/24', subtitle: 'Semua unit berhasil kirim pembaruan', trend: 6, color: 'blue' },
    ],
    spotlight: [
      { label: 'Wilayah perlu atensi', value: 'Puskesmas Harapan', detail: 'Coverage baru 68% terhadap target mingguan.' },
      { label: 'Verifikasi tercepat', value: 'Puskesmas Cempaka', detail: 'Waktu validasi rata-rata 3,8 jam.' },
      { label: 'Aksi tercepat', value: 'Tindak revisi', detail: '31 item revisi masih bisa dikejar sebelum rekap mingguan.' },
    ],
    funnel: [
      { label: 'Masuk', value: 1842, hint: 'Seluruh survey diterima' },
      { label: 'Dicek', value: 1498, hint: 'Sudah dibaca petugas' },
      { label: 'Valid', value: 1369, hint: 'Masuk agregasi' },
      { label: 'Revisi', value: 129, hint: 'Menunggu perbaikan' },
    ],
    quickActions: [
      { label: 'Audit Trail', path: '/admin/settings/audit', description: 'Lacak aktivitas perubahan dan approval penting.' },
      { label: 'Periode & Target', path: '/admin/settings/periods', description: 'Sesuaikan baseline target sebelum tutup pekan.' },
      { label: 'Monitoring Intervensi', path: '/admin/surveys/interventions', description: 'Pantau keluarga prioritas yang perlu tindak lanjut cepat.' },
      { label: 'Capaian Indikator', path: '/admin/reports/survey-indicators', description: 'Tinjau indikator yang mulai turun.' },
    ],
    activities: [
      { title: 'Puskesmas Harapan tertinggal', status: 'Butuh dukungan', tone: 'danger', meta: 'Harian', description: 'Jumlah kader aktif turun menjadi 74% dan memengaruhi cakupan survei.' },
      { title: 'Integrasi laporan stabil', status: 'On track', tone: 'info', meta: 'Mingguan', description: 'Rekap PHBS kabupaten sudah konsisten tanpa missing wilayah.' },
      { title: 'Master scoring terkunci', status: 'Aman', tone: 'success', meta: 'Mingguan', description: 'Tidak ada perubahan formula di periode berjalan.' },
    ],
    rows: [
      { area: 'Puskesmas Sukamaju', target: '420', realized: '404', coverage: '96%', valid: '97%', risk: 'Baik' },
      { area: 'Puskesmas Harapan', target: '380', realized: '259', coverage: '68%', valid: '79%', risk: 'Perlu eskalasi' },
      { area: 'Puskesmas Cempaka', target: '350', realized: '337', coverage: '96%', valid: '98%', risk: 'Baik' },
      { area: 'Puskesmas Mekarsari', target: '390', realized: '352', coverage: '90%', valid: '89%', risk: 'Pantau revisi' },
    ],
  },
  month: {
    summary: 'Rekap 30 hari terakhir untuk melihat keseimbangan target, kualitas validasi, dan beban intervensi.',
    cards: [
      { title: 'Survei Masuk', value: '7.960', subtitle: 'Capaian 92% dari target bulanan', trend: 11, color: 'teal' },
      { title: 'Antrian Validasi', value: '302', subtitle: 'Masih aman untuk SLA 48 jam', trend: -7, color: 'amber' },
      { title: 'Intervensi Aktif', value: '1.226', subtitle: '352 keluarga belum selesai tindak lanjut', trend: 13, color: 'rose' },
      { title: 'Sinkronisasi Unit', value: '24/24', subtitle: 'Semua dashboard bawah tersambung', trend: 2, color: 'blue' },
    ],
    spotlight: [
      { label: 'Wilayah perlu atensi', value: 'Kabupaten Barat', detail: 'Kontributor terbesar backlog intervensi bulan ini.' },
      { label: 'Validasi terbaik', value: 'Kec. Cempaka', detail: 'Rasio valid 96% dengan revisi paling rendah.' },
      { label: 'Aksi tercepat', value: 'Monitor coverage', detail: 'Tutup gap target bulanan melalui dashboard progress.' },
    ],
    funnel: [
      { label: 'Masuk', value: 7960, hint: 'Survei terkumpul' },
      { label: 'Dicek', value: 7354, hint: 'Sedang/selesai diperiksa' },
      { label: 'Valid', value: 7052, hint: 'Layak dilaporkan' },
      { label: 'Revisi', value: 302, hint: 'Perlu aksi lapangan' },
    ],
    quickActions: [
      { label: 'Dashboard Dinkes', path: '/dinkes/dashboard', description: 'Bandingkan tampilan eksekutif level kabupaten.' },
      { label: 'Dashboard Puskesmas', path: '/puskesmas/dashboard', description: 'Lihat titik kerja operasional di lapangan.' },
      { label: 'Dashboard Kader', path: '/kader/dashboard', description: 'Pastikan alur personal surveyor tetap ringan.' },
      { label: 'Manajemen Role & Menu', path: '/admin/settings/rbac', description: 'Audit akses jika perlu ada penyesuaian role.' },
    ],
    activities: [
      { title: 'Coverage bulanan stabil', status: 'Terkendali', tone: 'success', meta: 'Bulanan', description: 'Sebagian besar kecamatan berada di atas 88% target berjalan.' },
      { title: 'Indikator JKN turun', status: 'Perlu analisis', tone: 'warning', meta: 'Bulanan', description: 'Beberapa desa memperlihatkan penurunan kepesertaan valid pada hasil survei.' },
      { title: 'Kunjungan intervensi menumpuk', status: 'Perlu percepatan', tone: 'danger', meta: 'Bulanan', description: '352 keluarga belum selesai pada intervensi tahap kedua.' },
    ],
    rows: [
      { area: 'Kabupaten Tengah', target: '2.100', realized: '1.994', coverage: '95%', valid: '94%', risk: 'Baik' },
      { area: 'Kabupaten Barat', target: '1.840', realized: '1.564', coverage: '85%', valid: '86%', risk: 'Perlu eskalasi' },
      { area: 'Kabupaten Timur', target: '2.020', realized: '1.943', coverage: '96%', valid: '95%', risk: 'Stabil' },
      { area: 'Kabupaten Selatan', target: '2.000', realized: '1.859', coverage: '93%', valid: '91%', risk: 'Pantau revisi' },
    ],
  },
  semester: {
    summary: 'Sudut pandang semester untuk memastikan kesiapan eksekutif sebelum bergeser ke data riil dan pelaporan resmi.',
    cards: [
      { title: 'Survei Masuk', value: '44.280', subtitle: '94% dari target semester', trend: 10, color: 'teal' },
      { title: 'Antrian Validasi', value: '611', subtitle: 'Tertinggi berasal dari dua puskesmas', trend: -3, color: 'amber' },
      { title: 'Intervensi Aktif', value: '5.214', subtitle: '1.104 kasus masih terbuka', trend: 15, color: 'rose' },
      { title: 'Sinkronisasi Unit', value: '24/24', subtitle: 'Keseragaman menu dashboard terjaga', trend: 4, color: 'blue' },
    ],
    spotlight: [
      { label: 'Wilayah perlu atensi', value: 'Regional Barat', detail: 'Perlu kombinasi dukungan kader dan penguatan verifikasi.' },
      { label: 'Kontributor terbaik', value: 'Regional Timur', detail: 'IKS naik 0,08 dengan coverage 97%.' },
      { label: 'Aksi tercepat', value: 'Finalisasi laporan', detail: 'Siapkan ekspor rekap PHBS dan progress survey.' },
    ],
    funnel: [
      { label: 'Masuk', value: 44280, hint: 'Data semester' },
      { label: 'Dicek', value: 42110, hint: 'Sudah diproses petugas' },
      { label: 'Valid', value: 41499, hint: 'Siap pelaporan' },
      { label: 'Revisi', value: 611, hint: 'Perlu tindak lanjut' },
    ],
    quickActions: [
      { label: 'Rekap PHBS', path: '/admin/reports/phs-kabupaten', description: 'Finalisasi keluaran rekap per kecamatan dan puskesmas.' },
      { label: 'Laporan IKS', path: '/admin/reports/iks-wilayah', description: 'Tinjau status sehat, pra-sehat, dan tidak sehat.' },
      { label: 'Progress Survey', path: '/admin/reports/survey-progress', description: 'Bandingkan capaian wilayah sebelum rapat evaluasi.' },
      { label: 'Master Faskes', path: '/admin/master/faskes', description: 'Pastikan referensi fasilitas tetap sinkron.' },
    ],
    activities: [
      { title: 'Semester siap review', status: 'Eksekutif', tone: 'info', meta: 'Semester', description: 'Semua blok dashboard kini sudah dipetakan sesuai persona admin.' },
      { title: 'Backlog validasi menurun', status: 'Membaik', tone: 'success', meta: 'Semester', description: 'Penurunan backlog 18% dibanding semester sebelumnya.' },
      { title: 'Intervensi tahap dua', status: 'Fokus utama', tone: 'warning', meta: 'Semester', description: 'Perlu ketat memonitor keluarga dengan hipertensi dan perilaku merokok.' },
    ],
    rows: [
      { area: 'Regional Timur', target: '12.400', realized: '12.018', coverage: '97%', valid: '96%', risk: 'Baik' },
      { area: 'Regional Barat', target: '10.800', realized: '9.442', coverage: '87%', valid: '85%', risk: 'Perlu eskalasi' },
      { area: 'Regional Selatan', target: '10.500', realized: '9.991', coverage: '95%', valid: '92%', risk: 'Pantau revisi' },
      { area: 'Regional Tengah', target: '10.600', realized: '10.213', coverage: '96%', valid: '95%', risk: 'Stabil' },
    ],
  },
}

export const dinkesDashboardData = {
  years: ['2026', '2025'],
  focusAreas: ['Semua wilayah', 'Kabupaten Barat', 'Kabupaten Timur', 'Kabupaten Selatan'],
  statsByYear: {
    '2026': {
      cards: [
        { title: 'IKS Kabupaten', value: '0.682', subtitle: 'Naik 0.041 dari tahun lalu', trend: 6, color: 'teal' },
        { title: 'Keluarga Tersurvei', value: '124.592', subtitle: '91% terhadap target kabupaten', trend: 11, color: 'blue' },
        { title: 'Puskesmas On Track', value: '18/24', subtitle: '6 unit perlu percepatan coverage', trend: 2, color: 'emerald' },
        { title: 'Desa Prioritas', value: '37', subtitle: 'Fokus intervensi indikator dominan', trend: -5, color: 'amber' },
      ],
      rankings: [
        { name: 'Puskesmas Cempaka', iks: '0.78', coverage: '97%', trend: 'Naik stabil', status: 'Baik' },
        { name: 'Puskesmas Sukamaju', iks: '0.74', coverage: '94%', trend: 'Naik moderat', status: 'Baik' },
        { name: 'Puskesmas Harapan', iks: '0.63', coverage: '79%', trend: 'Butuh dorongan', status: 'Atensi' },
        { name: 'Puskesmas Mekarsari', iks: '0.67', coverage: '88%', trend: 'Fluktuatif', status: 'Pantau' },
      ],
      indicatorFocus: [
        { label: 'Merokok dalam rumah', percent: 41, tone: 'danger', note: 'Masih dominan di Barat dan Selatan.' },
        { label: 'Kepesertaan JKN', percent: 73, tone: 'warning', note: 'Turun tipis di desa pinggiran.' },
        { label: 'Akses jamban sehat', percent: 82, tone: 'info', note: 'Cukup baik, tapi belum merata.' },
      ],
      agenda: [
        { title: 'Review capaian triwulan', status: 'Minggu ini', tone: 'info', description: 'Siapkan bahan rapat dengan sorotan ranking puskesmas dan desa prioritas.', meta: 'Triwulan II' },
        { title: 'Pendampingan Puskesmas Harapan', status: 'Prioritas', tone: 'warning', description: 'Coverage tertinggal dan revisi survey lebih tinggi dari rata-rata.', meta: 'Operasional' },
        { title: 'Ekspor rekap kabupaten', status: 'Siap', tone: 'success', description: 'Data cukup rapi untuk simulasi keluaran PHBS kabupaten.', meta: 'Pelaporan' },
      ],
    },
    '2025': {
      cards: [
        { title: 'IKS Kabupaten', value: '0.641', subtitle: 'Menjadi baseline tahun sebelumnya', trend: 4, color: 'teal' },
        { title: 'Keluarga Tersurvei', value: '109.820', subtitle: '85% terhadap target kabupaten', trend: 7, color: 'blue' },
        { title: 'Puskesmas On Track', value: '15/24', subtitle: 'Banyak unit masih adaptasi target', trend: -3, color: 'emerald' },
        { title: 'Desa Prioritas', value: '44', subtitle: 'Lebih banyak wilayah perlu intervensi', trend: 8, color: 'amber' },
      ],
      rankings: [
        { name: 'Puskesmas Cempaka', iks: '0.72', coverage: '93%', trend: 'Stabil', status: 'Baik' },
        { name: 'Puskesmas Sukamaju', iks: '0.69', coverage: '89%', trend: 'Naik tipis', status: 'Baik' },
        { name: 'Puskesmas Mekarsari', iks: '0.61', coverage: '81%', trend: 'Fluktuatif', status: 'Pantau' },
        { name: 'Puskesmas Harapan', iks: '0.57', coverage: '72%', trend: 'Menurun', status: 'Atensi' },
      ],
      indicatorFocus: [
        { label: 'Merokok dalam rumah', percent: 45, tone: 'danger', note: 'Isu terbesar tahun lalu.' },
        { label: 'Kepesertaan JKN', percent: 70, tone: 'warning', note: 'Banyak keluarga belum tervalidasi.' },
        { label: 'Akses jamban sehat', percent: 79, tone: 'info', note: 'Capaian cukup, perlu pemerataan.' },
      ],
      agenda: [
        { title: 'Perbandingan baseline', status: 'Referensi', tone: 'info', description: 'Dataset ini dipakai untuk membaca tren kenaikan IKS di 2026.', meta: 'Historis' },
        { title: 'Evaluasi target tahunan', status: 'Selesai', tone: 'success', description: 'Target 2026 ditata ulang dari gap coverage 2025.', meta: 'Perencanaan' },
        { title: 'Wilayah risiko tinggi', status: 'Atensi', tone: 'warning', description: 'Kabupaten Barat dan Harapan mendominasi backlog intervensi.', meta: 'Risiko' },
      ],
    },
  },
}

export const puskesmasDashboardData = {
  filters: ['Semua desa', 'Sukamaju', 'Mekarjaya', 'Harapan', 'Cempaka'],
  stats: [
    { title: 'Survei Hari Ini', value: '84', subtitle: 'Target harian 96 kunjungan', trend: 12, color: 'teal' },
    { title: 'Menunggu Verifikasi', value: '27', subtitle: '9 item perlu revisi bukti', trend: -6, color: 'amber' },
    { title: 'Kader Aktif', value: '18/22', subtitle: 'Empat kader perlu dukungan lapangan', trend: 3, color: 'blue' },
    { title: 'Keluarga Prioritas', value: '63', subtitle: 'Masuk daftar intervensi bulan berjalan', trend: 9, color: 'rose' },
  ],
  queue: [
    { title: 'Survei baru belum diverifikasi', village: 'Sukamaju', count: 12, status: 'Prioritas', tone: 'warning', description: 'Terdapat 3 catatan bukti kunjungan yang belum lengkap.' },
    { title: 'Intervensi hipertensi belum dijadwalkan', village: 'Mekarjaya', count: 8, status: 'Tindak lanjut', tone: 'danger', description: 'Kunjungan rumah belum dibagi ke kader pendamping.' },
    { title: 'Coverage tertinggal target minggu ini', village: 'Harapan', count: 5, status: 'Pantau', tone: 'info', description: 'Perlu redistribusi keluarga sasaran ke dua kader cadangan.' },
  ],
  villages: [
    { desa: 'Sukamaju', survei: 142, valid: 128, revisi: 9, iks: '0.74', keluarga: 198, status: 'Stabil' },
    { desa: 'Mekarjaya', survei: 118, valid: 102, revisi: 11, iks: '0.68', keluarga: 176, status: 'Perlu intervensi' },
    { desa: 'Harapan', survei: 95, valid: 83, revisi: 8, iks: '0.59', keluarga: 161, status: 'Tertinggal' },
    { desa: 'Cempaka', survei: 131, valid: 124, revisi: 4, iks: '0.77', keluarga: 188, status: 'Baik' },
  ],
  kaderPerformance: [
    { name: 'Rina', completion: 92, visits: 31, drafts: 1, status: 'On track' },
    { name: 'Dewi', completion: 88, visits: 28, drafts: 2, status: 'On track' },
    { name: 'Asep', completion: 63, visits: 17, drafts: 4, status: 'Butuh dorongan' },
    { name: 'Nia', completion: 74, visits: 21, drafts: 3, status: 'Pantau' },
  ],
}

export const kaderDashboardData = {
  profile: {
    name: 'Rina Kurnia',
    village: 'Desa Sukamaju',
    cluster: 'RT 01-04 / RW 02',
    syncStatus: 'Sinkron terakhir 09:12 WIB',
  },
  cards: [
    { title: 'Survei Selesai', value: '120', subtitle: 'dari target 500 tahun ini', trend: 14, color: 'teal' },
    { title: 'Target Hari Ini', value: '5 keluarga', subtitle: '3 kunjungan sudah dilakukan', trend: 0, color: 'blue' },
    { title: 'Draft Aktif', value: '2', subtitle: 'Perlu diselesaikan sebelum sore', trend: -10, color: 'amber' },
    { title: 'Tindak Lanjut', value: '1 keluarga', subtitle: 'Masuk intervensi perilaku merokok', trend: 5, color: 'rose' },
  ],
  drafts: [
    { id: '1', familyHead: 'Budi Santoso', address: 'RT 01 / RW 02, Desa Sukamaju', lastUpdated: '10 Juni 2026, 10:00', progress: 78 },
    { id: '2', familyHead: 'Siti Aminah', address: 'RT 03 / RW 02, Desa Sukamaju', lastUpdated: '10 Juni 2026, 08:45', progress: 42 },
  ],
  schedule: [
    { title: 'Kunjungan keluarga prioritas', time: '10:30', status: 'Hari ini', tone: 'info', description: 'Keluarga Agus Salim untuk verifikasi indikator merokok dalam rumah.' },
    { title: 'Sinkronisasi setelah lapangan', time: '15:00', status: 'Wajib', tone: 'warning', description: 'Pastikan seluruh draft terkirim saat koneksi stabil.' },
    { title: 'Edukasi PHBS RT 03', time: '16:30', status: 'Opsional', tone: 'success', description: 'Catat hasil edukasi singkat ke log intervensi.' },
  ],
  quickActions: [
    { label: 'Mulai Survei Baru', path: '/kader/surveys/new', description: 'Langsung buka wizard survei keluarga.' },
    { label: 'Buka Draft', path: '/kader/surveys/drafts', description: 'Lanjutkan isian yang belum selesai.' },
    { label: 'Jadwal Intervensi', path: '/kader/interventions/schedule', description: 'Cek agenda tindak lanjut hari ini.' },
    { label: 'Pengaturan Akun', path: '/kader/profile/account', description: 'Perbarui profil kerja dan preferensi akun Anda.' },
  ],
}

export const simpleDashboardConfigs = {
  admin: {
    title: 'Dashboard Admin',
    description: 'Ringkasan kualitas proses survey, validasi, intervensi, dan coverage wilayah dalam satu tampilan sederhana.',
    icon: 'activity',
    filters: [
      { value: '2026', label: 'Tahun 2026' },
      { value: '2025', label: 'Tahun 2025' },
    ],
    dataByFilter: {
      '2026': {
        highlights: [
          { label: 'Backlog prioritas', value: '129 item' },
          { label: 'Unit perlu atensi', value: '6 puskesmas' },
          { label: 'Sinkronisasi', value: '24/24 aktif' },
        ],
        cards: [
          { label: 'Survei Masuk', value: '44.280', subtitle: '94% dari target semester', icon: 'users', color: 'blue' },
          { label: 'IKS Wilayah', value: '0.682', subtitle: 'Naik 0.041 dari baseline', icon: 'trending', color: 'teal' },
          { label: 'Intervensi Aktif', value: '5.214', subtitle: '1.104 kasus masih terbuka', icon: 'activity', color: 'amber' },
          { label: 'Kader Aktif', value: '1.820', subtitle: 'Tersebar di 24 unit kerja', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Survei & Validasi',
        trendCategories: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des'],
        trendSeries: [
          { name: 'Survei Masuk', data: [2800, 3100, 3280, 3450, 3690, 3820, 3950, 4020, 4160, 4380, 4510, 4720] },
          { name: 'Tervalidasi', data: [2440, 2860, 2980, 3120, 3380, 3520, 3660, 3750, 3890, 4020, 4170, 4310] },
        ],
        donutLabel: 'Proporsi Status Survey',
        donutSeries: [68, 22, 10],
        donutLabels: ['Valid', 'Revisi', 'Belum Dicek'],
        insightTitle: 'Insight Operasional Admin',
        insightDescription: 'Titik baca utama untuk pengambilan keputusan cepat di level pengendalian sistem.',
        insights: [
          { title: 'Validasi masih menjadi bottleneck utama', badge: 'Prioritas', description: 'Walau coverage wilayah tinggi, antrian validasi masih menahan kecepatan laporan final di beberapa kecamatan.' },
          { title: 'Wilayah Harapan perlu eskalasi lintas modul', badge: 'Atensi', description: 'Masalah tidak hanya pada coverage, tetapi juga revisi survey dan intervensi yang belum ditutup.' },
          { title: 'Sinkronisasi unit sudah stabil', badge: 'Baik', description: 'Seluruh unit aktif mengirim pembaruan, sehingga fokus admin bisa bergeser ke mutu data dan kecepatan approval.' },
        ],
        focusTitle: 'Fokus Admin Mingguan',
        focusDescription: 'Panel ini membedakan dashboard admin dari role lain: lebih banyak kontrol kualitas proses dan tata kelola.',
        focusItems: [
          { label: 'SLA validasi 48 jam', value: '82%', note: 'Masih ada gap terhadap target internal 90%.', progress: 82, status: 'Pantau' },
          { label: 'Coverage survey semester', value: '94%', note: 'Secara volume sudah baik dan tinggal dijaga konsistensinya.', progress: 94, status: 'Baik' },
          { label: 'Intervensi tertutup', value: '79%', note: 'Kasus tahap dua masih dominan pada perilaku merokok dan hipertensi.', progress: 79, status: 'Atensi' },
        ],
        tableTitle: 'Ringkasan Wilayah Prioritas',
        tableColumns: [
          { key: 'area', label: 'Wilayah' },
          { key: 'target', label: 'Target' },
          { key: 'realisasi', label: 'Realisasi' },
          { key: 'coverage', label: 'Coverage' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { area: 'Kec. Sukamaju', target: '12.400', realisasi: '12.018', coverage: '97%', status: 'Baik' },
          { area: 'Kec. Harapan', target: '10.800', realisasi: '9.442', coverage: '87%', status: 'Perlu Eskalasi' },
          { area: 'Kec. Cempaka', target: '10.500', realisasi: '9.991', coverage: '95%', status: 'Stabil' },
          { area: 'Kec. Mekarsari', target: '10.600', realisasi: '10.213', coverage: '96%', status: 'Baik' },
        ],
      },
      '2025': {
        highlights: [
          { label: 'Backlog prioritas', value: '174 item' },
          { label: 'Unit perlu atensi', value: '9 puskesmas' },
          { label: 'Sinkronisasi', value: '21/24 aktif' },
        ],
        cards: [
          { label: 'Survei Masuk', value: '39.840', subtitle: '88% dari target tahunan', icon: 'users', color: 'blue' },
          { label: 'IKS Wilayah', value: '0.641', subtitle: 'Baseline tahun sebelumnya', icon: 'trending', color: 'teal' },
          { label: 'Intervensi Aktif', value: '4.802', subtitle: 'Kasus terbuka lebih tinggi', icon: 'activity', color: 'amber' },
          { label: 'Kader Aktif', value: '1.744', subtitle: 'Distribusi unit belum merata', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Survei & Validasi',
        trendCategories: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des'],
        trendSeries: [
          { name: 'Survei Masuk', data: [2400, 2590, 2760, 2950, 3090, 3210, 3340, 3460, 3590, 3720, 3870, 4010] },
          { name: 'Tervalidasi', data: [2080, 2290, 2410, 2590, 2720, 2830, 2960, 3040, 3170, 3290, 3410, 3550] },
        ],
        donutLabel: 'Proporsi Status Survey',
        donutSeries: [63, 24, 13],
        donutLabels: ['Valid', 'Revisi', 'Belum Dicek'],
        insightTitle: 'Insight Operasional Admin',
        insightDescription: 'Perbandingan baseline untuk melihat area yang membaik dan yang masih perlu dikawal.',
        insights: [
          { title: 'Kinerja 2025 lebih berat di fase validasi', badge: 'Atensi', description: 'Porsi revisi dan belum dicek lebih tinggi sehingga laporan banyak tertahan di akhir periode.' },
          { title: 'Distribusi kader belum merata', badge: 'Pantau', description: 'Beberapa unit masih memiliki ketimpangan beban kerja yang terasa pada coverage dan follow-up.' },
          { title: 'Mutu data menjadi alasan utama rework dashboard', badge: 'Baik', description: 'Dashboard baru dibuat untuk memperjelas kondisi proses, bukan hanya menampilkan akumulasi angka.' },
        ],
        focusTitle: 'Fokus Admin Tahunan',
        focusDescription: 'Memberi konteks historis agar dashboard admin tidak serupa dengan dashboard eksekutif Dinkes.',
        focusItems: [
          { label: 'SLA validasi 48 jam', value: '74%', note: 'Jauh di bawah target dan menjadi alasan pengetatan proses 2026.', progress: 74, status: 'Atensi' },
          { label: 'Coverage survey tahunan', value: '88%', note: 'Masih tertinggal terhadap target, terutama di unit barat.', progress: 88, status: 'Pantau' },
          { label: 'Intervensi tertutup', value: '71%', note: 'Banyak keluarga belum tuntas pada tahap follow-up akhir.', progress: 71, status: 'Perlu Eskalasi' },
        ],
        tableTitle: 'Ringkasan Wilayah Prioritas',
        tableColumns: [
          { key: 'area', label: 'Wilayah' },
          { key: 'target', label: 'Target' },
          { key: 'realisasi', label: 'Realisasi' },
          { key: 'coverage', label: 'Coverage' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { area: 'Kec. Sukamaju', target: '11.900', realisasi: '10.890', coverage: '92%', status: 'Stabil' },
          { area: 'Kec. Harapan', target: '10.300', realisasi: '8.240', coverage: '80%', status: 'Perlu Eskalasi' },
          { area: 'Kec. Cempaka', target: '10.100', realisasi: '9.401', coverage: '93%', status: 'Baik' },
          { area: 'Kec. Mekarsari', target: '10.200', realisasi: '9.118', coverage: '89%', status: 'Pantau' },
        ],
      },
    },
  },
  dinkes: {
    title: 'Dashboard Dinkes',
    description: 'Tampilan sederhana untuk membaca IKS kabupaten, ranking unit, dan sebaran status keluarga sehat.',
    icon: 'activity',
    filters: [
      { value: '2026', label: 'Tahun 2026' },
      { value: '2025', label: 'Tahun 2025' },
    ],
    dataByFilter: {
      '2026': {
        highlights: [
          { label: 'Kabupaten terbaik', value: 'Cempaka' },
          { label: 'Desa prioritas', value: '37 desa' },
          { label: 'IKS naik', value: '+0.041' },
        ],
        cards: [
          { label: 'Keluarga Tersurvei', value: '124.592', subtitle: '91% terhadap target kabupaten', icon: 'users', color: 'blue' },
          { label: 'IKS Kabupaten', value: '0.682', subtitle: 'Naik 0.041 dari tahun lalu', icon: 'trending', color: 'teal' },
          { label: 'Desa Prioritas', value: '37', subtitle: 'Perlu intervensi indikator dominan', icon: 'activity', color: 'amber' },
          { label: 'Puskesmas On Track', value: '18/24', subtitle: '6 unit perlu percepatan', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Capaian Kabupaten',
        trendCategories: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des'],
        trendSeries: [
          { name: 'Keluarga Disurvei', data: [8400, 8800, 9100, 9440, 9820, 10160, 10320, 10640, 10880, 11140, 11320, 11670] },
          { name: 'IKS x10000', data: [6100, 6200, 6320, 6400, 6510, 6590, 6660, 6700, 6750, 6810, 6840, 6820] },
        ],
        donutLabel: 'Proporsi Status Keluarga',
        donutSeries: [65, 24, 11],
        donutLabels: ['Sehat', 'Tidak Sehat'],
        insightTitle: 'Insight Strategis Dinkes',
        insightDescription: 'Fokus pada komparasi wilayah dan indikator dominan, bukan proses teknis harian.',
        insights: [
          { title: 'IKS kabupaten tumbuh konsisten', badge: 'Baik', description: 'Perbaikan IKS berasal dari puskesmas dengan coverage tinggi dan kualitas validasi yang lebih stabil.' },
          { title: 'Puskesmas Harapan masih menjadi titik lemah', badge: 'Atensi', description: 'Ranking, coverage, dan arah tren menempatkan unit ini sebagai fokus pembinaan berikutnya.' },
          { title: 'Indikator merokok tetap isu dominan', badge: 'Prioritas', description: 'Walau sanitasi dan JKN mulai membaik, perilaku merokok masih paling besar menekan status keluarga sehat.' },
        ],
        focusTitle: 'Fokus Pembinaan Wilayah',
        focusDescription: 'Membedakan dashboard Dinkes sebagai ruang baca strategis lintas puskesmas dan kabupaten.',
        focusItems: [
          { label: 'Puskesmas on track', value: '75%', note: '18 dari 24 unit berada di jalur target coverage.', progress: 75, status: 'Baik' },
          { label: 'Desa sehat', value: '65%', note: 'Masih ada porsi cukup besar desa pra-sehat dan tidak sehat.', progress: 65, status: 'Pantau' },
          { label: 'Indikator merokok', value: '41%', note: 'Masih menjadi indikator dominan bermasalah pada wilayah barat dan selatan.', progress: 41, status: 'Prioritas' },
        ],
        tableTitle: 'Ranking Puskesmas',
        tableColumns: [
          { key: 'unit', label: 'Puskesmas' },
          { key: 'iks', label: 'IKS' },
          { key: 'coverage', label: 'Coverage' },
          { key: 'trend', label: 'Arah' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { unit: 'Puskesmas Cempaka', iks: '0.78', coverage: '97%', trend: 'Naik Stabil', status: 'Baik' },
          { unit: 'Puskesmas Sukamaju', iks: '0.74', coverage: '94%', trend: 'Naik Moderat', status: 'Baik' },
          { unit: 'Puskesmas Mekarsari', iks: '0.67', coverage: '88%', trend: 'Fluktuatif', status: 'Pantau' },
          { unit: 'Puskesmas Harapan', iks: '0.63', coverage: '79%', trend: 'Tertinggal', status: 'Atensi' },
        ],
      },
      '2025': {
        highlights: [
          { label: 'Kabupaten terbaik', value: 'Cempaka' },
          { label: 'Desa prioritas', value: '44 desa' },
          { label: 'IKS naik', value: 'baseline 0.641' },
        ],
        cards: [
          { label: 'Keluarga Tersurvei', value: '109.820', subtitle: '85% terhadap target kabupaten', icon: 'users', color: 'blue' },
          { label: 'IKS Kabupaten', value: '0.641', subtitle: 'Menjadi baseline evaluasi', icon: 'trending', color: 'teal' },
          { label: 'Desa Prioritas', value: '44', subtitle: 'Lebih banyak desa perlu intervensi', icon: 'activity', color: 'amber' },
          { label: 'Puskesmas On Track', value: '15/24', subtitle: 'Masih banyak unit adaptasi target', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Capaian Kabupaten',
        trendCategories: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des'],
        trendSeries: [
          { name: 'Keluarga Disurvei', data: [7300, 7580, 7810, 8140, 8420, 8670, 8910, 9160, 9380, 9620, 9850, 10020] },
          { name: 'IKS x10000', data: [5700, 5780, 5890, 6010, 6090, 6160, 6230, 6280, 6340, 6390, 6420, 6410] },
        ],
        donutLabel: 'Proporsi Status Keluarga',
        donutSeries: [61, 26, 13],
        donutLabels: ['Sehat', 'Tidak Sehat'],
        insightTitle: 'Insight Strategis Dinkes',
        insightDescription: 'Baseline historis untuk membantu membaca progres kabupaten dari tahun ke tahun.',
        insights: [
          { title: 'Gap antar puskesmas masih tinggi', badge: 'Atensi', description: 'Perbedaan coverage dan IKS antar unit menunjukkan perlunya pembinaan yang lebih terarah.' },
          { title: 'Keluarga pra-sehat masih mendominasi transisi', badge: 'Pantau', description: 'Banyak keluarga belum turun ke tidak sehat, tetapi juga belum cukup kuat untuk masuk kategori sehat.' },
          { title: 'Data ini menjadi dasar target 2026', badge: 'Baik', description: 'Struktur dashboard dibuat agar pembacaan tren historis tetap mudah setelah data riil dihubungkan.' },
        ],
        focusTitle: 'Fokus Pembinaan Wilayah',
        focusDescription: 'Memberi konteks strategis yang berbeda jelas dari dashboard admin dan puskesmas.',
        focusItems: [
          { label: 'Puskesmas on track', value: '63%', note: 'Baru 15 dari 24 unit yang stabil terhadap target.', progress: 63, status: 'Pantau' },
          { label: 'Desa sehat', value: '61%', note: 'Masih cukup banyak desa yang belum beranjak dari kategori pra-sehat.', progress: 61, status: 'Atensi' },
          { label: 'Indikator merokok', value: '45%', note: 'Masalah dominan yang paling menahan pertumbuhan IKS tahun sebelumnya.', progress: 45, status: 'Prioritas' },
        ],
        tableTitle: 'Ranking Puskesmas',
        tableColumns: [
          { key: 'unit', label: 'Puskesmas' },
          { key: 'iks', label: 'IKS' },
          { key: 'coverage', label: 'Coverage' },
          { key: 'trend', label: 'Arah' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { unit: 'Puskesmas Cempaka', iks: '0.72', coverage: '93%', trend: 'Stabil', status: 'Baik' },
          { unit: 'Puskesmas Sukamaju', iks: '0.69', coverage: '89%', trend: 'Naik Tipis', status: 'Baik' },
          { unit: 'Puskesmas Mekarsari', iks: '0.61', coverage: '81%', trend: 'Fluktuatif', status: 'Pantau' },
          { unit: 'Puskesmas Harapan', iks: '0.57', coverage: '72%', trend: 'Menurun', status: 'Atensi' },
        ],
      },
    },
  },
  puskesmas: {
    title: 'Dashboard Puskesmas',
    description: 'Ringkasan operasional puskesmas untuk survey masuk, verifikasi, keluarga prioritas, dan capaian desa.',
    icon: 'activity',
    filters: [
      { value: 'semester-1', label: 'Semester 1' },
      { value: 'semester-2', label: 'Semester 2' },
    ],
    dataByFilter: {
      'semester-1': {
        highlights: [
          { label: 'Desa tertinggi', value: 'Cempaka' },
          { label: 'Verifikasi tertunda', value: '127 item' },
          { label: 'Kader aktif', value: '18 dari 22' },
        ],
        cards: [
          { label: 'Survei Masuk', value: '3.842', subtitle: 'Rata-rata 640 survei per bulan', icon: 'users', color: 'blue' },
          { label: 'Menunggu Verifikasi', value: '127', subtitle: '31 item prioritas revisi', icon: 'trending', color: 'teal' },
          { label: 'Keluarga Prioritas', value: '263', subtitle: 'Masuk jadwal intervensi aktif', icon: 'activity', color: 'amber' },
          { label: 'Kader Aktif', value: '18/22', subtitle: '4 kader perlu pendampingan', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Survey & Verifikasi',
        trendCategories: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun'],
        trendSeries: [
          { name: 'Survei Masuk', data: [520, 580, 610, 664, 701, 766] },
          { name: 'Terverifikasi', data: [470, 531, 552, 608, 649, 705] },
        ],
        donutLabel: 'Proporsi Status Verifikasi',
        donutSeries: [72, 18, 10],
        donutLabels: ['Valid', 'Revisi', 'Antrian'],
        insightTitle: 'Insight Operasional Puskesmas',
        insightDescription: 'Membantu kepala puskesmas dan verifikator membaca beban kerja lapangan secara cepat.',
        insights: [
          { title: 'Sukamaju menjadi kontributor volume terbesar', badge: 'Baik', description: 'Desa ini menyumbang jumlah survey paling tinggi dengan kualitas validasi yang relatif aman.' },
          { title: 'Mekarjaya perlu intervensi lebih agresif', badge: 'Atensi', description: 'IKS masih tertahan karena revisi cukup tinggi dan keluarga prioritas belum banyak ditutup.' },
          { title: 'Harapan tertinggal pada dua sisi sekaligus', badge: 'Prioritas', description: 'Coverage rendah dan kualitas validasi belum kuat, sehingga perlu redistribusi kerja kader.' },
        ],
        focusTitle: 'Fokus Pengelolaan Wilayah',
        focusDescription: 'Membedakan dashboard puskesmas sebagai alat komando operasional, bukan dashboard strategis kabupaten.',
        focusItems: [
          { label: 'Rasio validasi desa', value: '72%', note: 'Masih ada ruang perbaikan untuk mengejar SLA verifikasi internal.', progress: 72, status: 'Pantau' },
          { label: 'Kader aktif lapangan', value: '82%', note: 'Empat kader perlu dorongan agar distribusi keluarga lebih seimbang.', progress: 82, status: 'Baik' },
          { label: 'Intervensi prioritas selesai', value: '69%', note: 'Kunjungan tindak lanjut hipertensi dan merokok masih perlu dipercepat.', progress: 69, status: 'Atensi' },
        ],
        tableTitle: 'Capaian Desa',
        tableColumns: [
          { key: 'desa', label: 'Desa' },
          { key: 'survei', label: 'Survei' },
          { key: 'valid', label: 'Valid' },
          { key: 'iks', label: 'IKS' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { desa: 'Sukamaju', survei: '142', valid: '128', iks: '0.74', status: 'Stabil' },
          { desa: 'Mekarjaya', survei: '118', valid: '102', iks: '0.68', status: 'Perlu Intervensi' },
          { desa: 'Harapan', survei: '95', valid: '83', iks: '0.59', status: 'Tertinggal' },
          { desa: 'Cempaka', survei: '131', valid: '124', iks: '0.77', status: 'Baik' },
        ],
      },
      'semester-2': {
        highlights: [
          { label: 'Desa tertinggi', value: 'Cempaka' },
          { label: 'Verifikasi tertunda', value: '96 item' },
          { label: 'Kader aktif', value: '20 dari 22' },
        ],
        cards: [
          { label: 'Survei Masuk', value: '4.116', subtitle: 'Ada kenaikan performa lapangan', icon: 'users', color: 'blue' },
          { label: 'Menunggu Verifikasi', value: '96', subtitle: 'Backlog lebih rendah', icon: 'trending', color: 'teal' },
          { label: 'Keluarga Prioritas', value: '241', subtitle: 'Intervensi mulai lebih tertata', icon: 'activity', color: 'amber' },
          { label: 'Kader Aktif', value: '20/22', subtitle: 'Dua kader masih tertinggal', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Survey & Verifikasi',
        trendCategories: ['Jul', 'Ags', 'Sep', 'Okt', 'Nov', 'Des'],
        trendSeries: [
          { name: 'Survei Masuk', data: [640, 672, 689, 701, 706, 708] },
          { name: 'Terverifikasi', data: [604, 638, 651, 669, 681, 688] },
        ],
        donutLabel: 'Proporsi Status Verifikasi',
        donutSeries: [76, 15, 9],
        donutLabels: ['Valid', 'Revisi', 'Antrian'],
        insightTitle: 'Insight Operasional Puskesmas',
        insightDescription: 'Perbaikan semester kedua difokuskan pada penurunan backlog dan penguatan kader aktif.',
        insights: [
          { title: 'Backlog verifikasi berhasil turun', badge: 'Baik', description: 'Jumlah item tertunda menurun sehingga ritme pelaporan menjadi lebih stabil.' },
          { title: 'Harapan mulai membaik tetapi belum aman', badge: 'Pantau', description: 'Coverage dan IKS naik, namun desa ini masih perlu pengawasan lebih rapat dibanding desa lain.' },
          { title: 'Kinerja kader lebih merata', badge: 'Baik', description: 'Jumlah kader aktif meningkat dan distribusi kunjungan lapangan terasa lebih sehat.' },
        ],
        focusTitle: 'Fokus Pengelolaan Wilayah',
        focusDescription: 'Menjaga dashboard tetap ringkas tetapi memberi konteks operasional yang cukup dalam.',
        focusItems: [
          { label: 'Rasio validasi desa', value: '76%', note: 'Mutu verifikasi lebih baik dibanding semester sebelumnya.', progress: 76, status: 'Baik' },
          { label: 'Kader aktif lapangan', value: '91%', note: 'Dua kader masih perlu dukungan, namun secara umum ritme lapangan membaik.', progress: 91, status: 'Baik' },
          { label: 'Intervensi prioritas selesai', value: '74%', note: 'Perlu dorongan akhir untuk keluarga dengan follow-up berulang.', progress: 74, status: 'Pantau' },
        ],
        tableTitle: 'Capaian Desa',
        tableColumns: [
          { key: 'desa', label: 'Desa' },
          { key: 'survei', label: 'Survei' },
          { key: 'valid', label: 'Valid' },
          { key: 'iks', label: 'IKS' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { desa: 'Sukamaju', survei: '151', valid: '141', iks: '0.77', status: 'Baik' },
          { desa: 'Mekarjaya', survei: '127', valid: '115', iks: '0.70', status: 'Stabil' },
          { desa: 'Harapan', survei: '109', valid: '94', iks: '0.63', status: 'Pantau' },
          { desa: 'Cempaka', survei: '139', valid: '131', iks: '0.79', status: 'Baik' },
        ],
      },
    },
  },
  kader: {
    title: 'Dashboard Kader',
    description: 'Tampilan ringkas untuk memantau target kunjungan, draft survey, tindak lanjut, dan progres keluarga binaan.',
    icon: 'activity',
    filters: [
      { value: 'minggu-ini', label: 'Minggu Ini' },
      { value: 'bulan-ini', label: 'Bulan Ini' },
    ],
    dataByFilter: {
      'minggu-ini': {
        highlights: [
          { label: 'Wilayah binaan', value: 'RT 01-04 / RW 02' },
          { label: 'Sinkron terakhir', value: '09:12 WIB' },
          { label: 'Kunjungan hari ini', value: '3 keluarga' },
        ],
        cards: [
          { label: 'Survei Selesai', value: '24', subtitle: 'Dari target 30 keluarga', icon: 'users', color: 'blue' },
          { label: 'Progress Target', value: '80%', subtitle: 'Sudah 5 hari on track', icon: 'trending', color: 'teal' },
          { label: 'Draft Aktif', value: '2', subtitle: 'Perlu diselesaikan hari ini', icon: 'activity', color: 'amber' },
          { label: 'Tindak Lanjut', value: '1', subtitle: 'Keluarga prioritas aktif', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Kunjungan Harian',
        trendCategories: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
        trendSeries: [
          { name: 'Kunjungan', data: [3, 4, 5, 3, 4, 3, 2] },
          { name: 'Survey Selesai', data: [2, 4, 4, 3, 4, 3, 2] },
        ],
        donutLabel: 'Proporsi Aktivitas Kader',
        donutSeries: [62, 23, 15],
        donutLabels: ['Selesai', 'Draft', 'Follow-up'],
        insightTitle: 'Insight Kerja Lapangan',
        insightDescription: 'Membantu kader tahu apa yang harus dilanjutkan sekarang, bukan sekadar melihat angka capaian.',
        insights: [
          { title: 'Target mingguan masih aman', badge: 'Baik', description: 'Progress 80% menunjukkan ritme kunjungan cukup sehat jika dua draft segera ditutup.' },
          { title: 'Draft menjadi risiko utama hari ini', badge: 'Prioritas', description: 'Semakin lama draft tertahan, semakin besar peluang kehilangan detail hasil kunjungan lapangan.' },
          { title: 'Follow-up perlu waktu khusus', badge: 'Pantau', description: 'Keluarga intervensi tidak banyak, tetapi membutuhkan perhatian lebih tinggi dibanding survey biasa.' },
        ],
        focusTitle: 'Fokus Kerja Kader',
        focusDescription: 'Dibedakan dari role lain dengan sudut pandang personal, harian, dan sangat actionable.',
        focusItems: [
          { label: 'Progress target minggu ini', value: '80%', note: 'Perlu 6 survey lagi untuk menutup target penuh.', progress: 80, status: 'Baik' },
          { label: 'Draft yang harus diselesaikan', value: '2 item', note: 'Utamakan keluarga dengan progress di atas 70% agar cepat selesai.', progress: 60, status: 'Prioritas' },
          { label: 'Kunjungan follow-up', value: '1 keluarga', note: 'Butuh pencatatan detail karena terkait intervensi perilaku merokok.', progress: 35, status: 'Pantau' },
        ],
        tableTitle: 'Keluarga yang Sedang Ditangani',
        tableColumns: [
          { key: 'keluarga', label: 'Keluarga' },
          { key: 'alamat', label: 'Alamat' },
          { key: 'progress', label: 'Progress' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { keluarga: 'Budi Santoso', alamat: 'RT 01 / RW 02', progress: '78%', status: 'Draft' },
          { keluarga: 'Siti Aminah', alamat: 'RT 03 / RW 02', progress: '42%', status: 'Draft' },
          { keluarga: 'Agus Salim', alamat: 'RT 04 / RW 02', progress: 'Follow-up', status: 'Intervensi' },
          { keluarga: 'Wati Nurhayati', alamat: 'RT 02 / RW 03', progress: '100%', status: 'Selesai' },
        ],
      },
      'bulan-ini': {
        highlights: [
          { label: 'Wilayah binaan', value: 'RT 01-04 / RW 02' },
          { label: 'Sinkron terakhir', value: '09:12 WIB' },
          { label: 'Kunjungan bulan ini', value: '120 selesai' },
        ],
        cards: [
          { label: 'Survei Selesai', value: '120', subtitle: 'Dari target 140 keluarga', icon: 'users', color: 'blue' },
          { label: 'Progress Target', value: '86%', subtitle: 'Masih on track terhadap target', icon: 'trending', color: 'teal' },
          { label: 'Draft Aktif', value: '5', subtitle: 'Tersebar di 3 RT', icon: 'activity', color: 'amber' },
          { label: 'Tindak Lanjut', value: '9', subtitle: 'Perlu kunjungan lanjutan', icon: 'file', color: 'purple' },
        ],
        trendLabel: 'Tren Kunjungan Mingguan',
        trendCategories: ['M1', 'M2', 'M3', 'M4'],
        trendSeries: [
          { name: 'Kunjungan', data: [26, 31, 33, 35] },
          { name: 'Survey Selesai', data: [23, 29, 31, 37] },
        ],
        donutLabel: 'Proporsi Aktivitas Kader',
        donutSeries: [70, 18, 12],
        donutLabels: ['Selesai', 'Draft', 'Follow-up'],
        insightTitle: 'Insight Kerja Lapangan',
        insightDescription: 'Memberi konteks bulanan yang tetap sederhana untuk memantau ritme kerja pribadi kader.',
        insights: [
          { title: 'Capaian bulanan sudah kuat', badge: 'Baik', description: 'Progress 86% menandakan target masih realistis tercapai tanpa menambah beban terlalu besar.' },
          { title: 'Draft tersebar di beberapa RT', badge: 'Pantau', description: 'Penyebaran draft ke banyak titik membuat kebutuhan sinkronisasi dan penutupan data lebih penting.' },
          { title: 'Follow-up mulai bertambah', badge: 'Atensi', description: 'Semakin banyak keluarga masuk tindak lanjut, sehingga perlu penjadwalan yang lebih tertib.' },
        ],
        focusTitle: 'Fokus Kerja Kader',
        focusDescription: 'Menjaga dashboard kader tetap informatif tanpa berubah menjadi dashboard analitik berat.',
        focusItems: [
          { label: 'Progress target bulan ini', value: '86%', note: 'Masih dalam jalur aman untuk menutup target 140 keluarga.', progress: 86, status: 'Baik' },
          { label: 'Draft aktif lintas RT', value: '5 item', note: 'Perlu dirapikan agar tidak menumpuk menjelang akhir bulan.', progress: 52, status: 'Pantau' },
          { label: 'Kunjungan follow-up', value: '9 keluarga', note: 'Prioritaskan keluarga dengan status intervensi terbuka paling lama.', progress: 46, status: 'Atensi' },
        ],
        tableTitle: 'Keluarga yang Sedang Ditangani',
        tableColumns: [
          { key: 'keluarga', label: 'Keluarga' },
          { key: 'alamat', label: 'Alamat' },
          { key: 'progress', label: 'Progress' },
          { key: 'status', label: 'Status' },
        ],
        tableRows: [
          { keluarga: 'Budi Santoso', alamat: 'RT 01 / RW 02', progress: '78%', status: 'Draft' },
          { keluarga: 'Siti Aminah', alamat: 'RT 03 / RW 02', progress: '42%', status: 'Draft' },
          { keluarga: 'Agus Salim', alamat: 'RT 04 / RW 02', progress: 'Follow-up', status: 'Intervensi' },
          { keluarga: 'Wati Nurhayati', alamat: 'RT 02 / RW 03', progress: '100%', status: 'Selesai' },
        ],
      },
    },
  },
}
